Repository michaeldera/edliz, pull requests merged in 2019-05, with the labels that each got.

#43 Bugfix/ui improvements
  src/Components/Home/Home.js
  src/Components/Home/github.svg
  src/Components/Home/home-wheelchair.png
  src/Components/Home/home.css
  src/Components/Home/medicine.svg
  src/Components/RoundedBtn/RoundedBtn.css
  src/index.css
Labels: bug

#49 bugfix Maximum Range Exceeded Error
  src/stores/EdlizStore.js
Labels: bug

#48 Chapter3
  src/Data/Chapters/chapter_three.js
Labels: Content

#53 Bug Fix/Scrolling Thumb
  README.md
  src/Views/ReaderScreen/readerscreen.css
Labels: bug, enhancement
